2025-07-29 12:25:19,482 - ERROR - root - /usr/local/lib/python3.10/dist-packages/aiomysql/cursors.py:239: Warning: Table 'users' already exists
  await self._query(query)
2025-07-29 12:25:19,727 - ERROR - root - /usr/local/lib/python3.10/dist-packages/aiomysql/cursors.py:239: Warning: Table 'userbots' already exists
  await self._query(query)
2025-07-29 12:25:19,974 - ERROR - root - /usr/local/lib/python3.10/dist-packages/aiomysql/cursors.py:239: Warning: Table 'commits' already exists
  await self._query(query)
2025-07-29 12:25:20,096 - ERROR - root - /usr/local/lib/python3.10/dist-packages/aiomysql/cursors.py:239: Warning: Table 'commit_votes' already exists
  await self._query(query)
2025-07-29 12:25:20,217 - ERROR - root - /usr/local/lib/python3.10/dist-packages/aiomysql/cursors.py:239: Warning: Table 'userbot_shared' already exists
  await self._query(query)
2025-07-29 12:25:38,211 - ERROR - system_manager - TIMEOUT on [51.250.123.60]. Command: echo 1
2025-07-29 12:25:50,929 - ERROR - system_manager - TIMEOUT on [51.250.123.60]. Command: top -bn1 | awk '/^%Cpu/ {print $2+$4}' && echo '---' && free -m | awk 'NR==2{printf "%d|%d", $3, $2}' && echo '---' && df -h / | awk 'NR==2{printf "%s|%s|%s", $5, $3, $2}' && echo '---' && uptime -p && echo '---' && nproc
